### ISSUE TITLE
1 Issue and a question.

### ISSUE THREAD

**Issue by gdfsgdfg** [Mikusch/source-vehicles#26]
While the Buggy sounds seem to work fine, Airboat is silent as an owl, I'm gonna guess the TF2's hl2 files doesn't provide sounds for the airboat right?

Another very specific issue happens in cp_dustbowl but could also be affecting other maps that use breakable props or something of the sort, players phase through those breakable barrels which doesn't happen when I disable the plugin so its affecting their "solid" state somehow.

**Comment by Mikusch** [comment]
Airboat sounds are hardcoded in the HL2 airboat class, which is not present in TF2 code. The jeep however had its sounds specified within the vehicle script. Don't ask me why, just how Valve implemented it in 2004.

I can't reproduce the issue with breakable props. Spawning a vehicle on cp_dustbowl, they collide with it just fine.

**Comment by gdfsgdfg** [comment]
I meant the players clip through the barrels not the vehicles. You don't even need to spawn a vehicle, Its just when the plugin is turned on.

**Comment by Mikusch** [comment]
Seems to be related to `sv_turbophysics 0`. The plugin changes this convar to allow vehicles to collide with players.

What you are describing is actually intended behavior for [prop_physics_multiplayer](https://developer.valvesoftware.com/wiki/Prop_physics_multiplayer).
