### ISSUE TITLE
Black Mesa 

### ISSUE THREAD

**Issue by yurakone** [Mikusch/source-vehicles#30]
_[SM] Unable to load plugin "vehicles.smx": Native "SoundScript.Count.get" was not found_

```
  SourceMod Version Information:
    SourceMod Version: 1.11.0.6888
    SourcePawn Engine: 1.11.0.6888, jit-x86 (build 1.11.0.6888)
    SourcePawn API: v1 = 5, v2 = 16
    Compiled on: Jun  6 2022 12:45:32
    Built from: https://github.com/alliedmodders/sourcemod/commit/5c0ae11a
    Build ID: 6888:5c0ae11a
```

**Comment by Mikusch** [comment]
I'm not too familiar with Black Mesa. It's possible that the LoadSoundScript extension does not work for this game anymore. Try using the plugin without the extension.

**Comment by Alienmario** [comment]
This appears to be the error you get without the extension.

**Comment by yurakone** [comment]
Solved. Found and installed soundscript plugin.
